project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - wild.qmd
      - try_me.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



