project:
  type: website
  output-dir: docs

website:
  title: "Powell Sheagren"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio
      - href: Files/Resume.pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



